version: "3"
services:
  # Database
  mongo:
    image: mongo
    ports:
     - "27017:27017"
  # Cache
  redis:
    image: "redis:alpine"
  # API
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.web
    ports:
     - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017
    depends_on:
     - mongo
  # Worker
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.worker
    environment:
     - MONGODB_URI=mongodb://mongo:27017
     - ETH_NODE=wss://mainnet.eth.aragon.network/ws
     - REDIS_URL=redis://redis:6379
    depends_on:
     - mongo
     - redis
  # Website
  website:
    build:
      context: ./website
      dockerfile: Dockerfile.frontend
      args:
        API_URL: "http://localhost:3000"
    ports:
    - "8888:80"
    depends_on:
    - api
    - worker
